import React, { useMemo, useState } from 'react';
import { Search, ChevronDown, CircleHelp, MessageCircle, Phone, ShieldCheck, Truck, WalletCards } from 'lucide-react';
import { useDelivery } from '../../context/DeliveryContext';

export const HelpPage: React.FC = () => {
  const { platformSettings, setActivePage } = useDelivery();
  const [openFaq, setOpenFaq] = useState<number | null>(0);
  const [query, setQuery] = useState('');
  const [category, setCategory] = useState('All topics');
  const faqs = [
    { group: 'Orders & delivery', q: 'Where can I follow my order?', a: 'Open My Orders to view the latest order status and any delivery progress shown in the app. If the status seems incorrect or has not changed, contact support and include your order reference.' },
    { group: 'Orders & delivery', q: 'Can I cancel an order?', a: 'Cancellation depends on the order status and whether the restaurant has started preparing it. Contact support as soon as possible and include your order reference. A cancellation or refund is not guaranteed until the request has been reviewed.' },
    { group: 'Orders & delivery', q: 'What if my order is late or incomplete?', a: 'Open a support ticket and select Order or delivery, or Refund or missing item. Tell us what is missing or delayed and include the order reference so the team can review the details.' },
    { group: 'Payments & refunds', q: 'What should I do if a payment is pending or looks incorrect?', a: 'Check your bank or payment provider for the latest status before trying again. Keep the transaction reference and submit a Payment or wallet ticket if the status remains unclear. Never share your PIN, password, or one-time code.' },
    { group: 'Payments & refunds', q: 'How do I request a refund?', a: 'Submit a Refund or missing item ticket with your order reference, a short explanation, and any relevant transaction reference. The team will review the details and explain the available next steps.' },
    { group: 'Account & privacy', q: 'What information should I send to support?', a: 'Include the email associated with your account and relevant order or transaction references. Only share information needed to investigate your request. Never send passwords, one-time codes, bank PINs, or full card details.' },
    { group: 'Account & privacy', q: 'How do I see the team’s response?', a: 'Keep the ticket reference after submitting your request. Use Contact Support to check its status with the ticket reference and the same email address used when you submitted it.' },
    { group: 'Restaurants & partnerships', q: 'How can a restaurant or business contact Veyrang?', a: 'Use the partnership option available in the app, or submit a support ticket and choose Restaurant partnership. Include your business name and a reliable contact email.' }
  ];
  const categories = ['All topics', ...Array.from(new Set(faqs.map(f => f.group)))];
  const filteredFaqs = useMemo(() => faqs.filter(f => (category === 'All topics' || f.group === category) && (f.q + ' ' + f.a + ' ' + f.group).toLowerCase().includes(query.trim().toLowerCase())), [query, category]);
  const whatsappNumber = (platformSettings?.cms_whatsapp_phone || '').replace(/\D/g, '');
  const phone = platformSettings?.cms_support_phone || '';

  return (
    <main className="min-h-[70vh] bg-slate-50 pb-16">
      <section className="relative overflow-hidden bg-slate-950 text-white">
        <div className="absolute inset-0 opacity-20" style={{ backgroundImage: 'radial-gradient(circle at 80% 20%, #f97316 0, transparent 34%), radial-gradient(circle at 10% 100%, #475569 0, transparent 38%)' }} />
        <div className="relative mx-auto max-w-6xl px-5 py-12 sm:px-8 sm:py-16">
          <p className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/5 px-3 py-1.5 text-xs font-semibold tracking-wide text-orange-200"><CircleHelp className="h-4 w-4" /> VEYRANG HELP CENTRE</p>
          <h1 className="mt-4 max-w-3xl text-3xl font-bold tracking-tight sm:text-5xl">{platformSettings?.cms_help_title || 'Answers first. Real support when you need it.'}</h1>
          <p className="mt-4 max-w-2xl text-sm leading-6 text-slate-300 sm:text-base">{platformSettings?.cms_help_subtitle || 'Find guidance for orders, delivery, payments, your account and restaurant partnerships. If you need help with a specific order, our ticket system keeps the conversation connected to your request.'}</p>
          <button onClick={() => setActivePage('contact')} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-orange-600 px-5 py-3 text-sm font-bold text-white transition hover:bg-orange-700">Contact support <MessageCircle className="h-4 w-4" /></button>
        </div>
      </section>
      <div className="mx-auto grid max-w-6xl gap-6 px-4 py-8 sm:px-8 lg:grid-cols-[minmax(0,1fr)_300px] lg:py-10">
        <section className="min-w-0 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7">
          <div className="mb-6"><p className="text-xs font-bold uppercase tracking-widest text-orange-600">Help centre</p><h2 className="mt-2 text-2xl font-bold tracking-tight text-slate-950">Frequently asked questions</h2><p className="mt-2 text-sm leading-6 text-slate-500">Search for a topic or browse the answers below.</p></div>
          <label className="relative block"><span className="sr-only">Search help articles</span><Search className="pointer-events-none absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search orders, refunds, payments…" className="w-full rounded-xl border border-slate-200 bg-slate-50 py-3 pl-11 pr-4 text-sm text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-orange-500 focus:ring-4 focus:ring-orange-100" /></label>
          <div className="mt-4 flex gap-2 overflow-x-auto pb-2" aria-label="FAQ categories">{categories.map(c => <button key={c} onClick={() => setCategory(c)} className={'shrink-0 rounded-full border px-3.5 py-2 text-xs font-semibold transition ' + (category === c ? 'border-slate-950 bg-slate-950 text-white' : 'border-slate-200 bg-white text-slate-600 hover:border-slate-400')}>{c}</button>)}</div>
          <div className="mt-4 space-y-3">{filteredFaqs.map(faq => { const idx = faqs.indexOf(faq); const isOpen = openFaq === idx; return <div key={faq.q} className="overflow-hidden rounded-xl border border-slate-200"><button aria-expanded={isOpen} onClick={() => setOpenFaq(isOpen ? null : idx)} className="flex w-full items-center justify-between gap-4 p-4 text-left transition hover:bg-slate-50 sm:p-5"><span><span className="mb-1.5 block text-[10px] font-bold uppercase tracking-widest text-orange-600">{faq.group}</span><span className="text-sm font-semibold leading-6 text-slate-900">{faq.q}</span></span><ChevronDown className={'h-4 w-4 shrink-0 text-slate-500 transition-transform ' + (isOpen ? 'rotate-180' : '')} /></button>{isOpen && <div className="border-t border-slate-100 bg-slate-50/70 px-4 py-4 text-sm leading-6 text-slate-600 sm:px-5">{faq.a}</div>}</div>; })}{filteredFaqs.length === 0 && <div className="rounded-xl border border-dashed border-slate-300 px-5 py-10 text-center"><Search className="mx-auto h-6 w-6 text-slate-400" /><h3 className="mt-3 text-sm font-bold text-slate-900">No matching answers</h3><p className="mt-1 text-sm text-slate-500">Try another keyword or choose a different topic.</p><button onClick={() => { setQuery(''); setCategory('All topics'); }} className="mt-4 text-sm font-semibold text-orange-700 hover:text-orange-800">Clear search</button></div>}</div>
        </section>
        <aside className="space-y-4">
          <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-orange-50 text-orange-700"><MessageCircle className="h-5 w-5" /></div><h2 className="mt-4 text-lg font-bold text-slate-950">Still need help?</h2><p className="mt-2 text-sm leading-6 text-slate-500">Send your question to the support team and keep a reference you can use to check for updates.</p><button onClick={() => setActivePage('contact')} className="mt-4 w-full rounded-xl bg-slate-950 px-4 py-3 text-sm font-bold text-white transition hover:bg-slate-800">Open a support ticket</button></div>
          <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h3 className="text-sm font-bold text-slate-950">Helpful reminders</h3><div className="mt-4 space-y-4"><div className="flex items-start gap-3"><span className="rounded-xl bg-orange-50 p-2.5 text-orange-700"><Truck className="h-5 w-5" /></span><div><p className="text-sm font-semibold text-slate-900">Order support</p><p className="mt-1 text-xs leading-5 text-slate-500">Include your order reference and a clear description.</p></div></div><div className="flex items-start gap-3"><span className="rounded-xl bg-emerald-50 p-2.5 text-emerald-700"><WalletCards className="h-5 w-5" /></span><div><p className="text-sm font-semibold text-slate-900">Payment support</p><p className="mt-1 text-xs leading-5 text-slate-500">Keep transaction references; never share payment secrets.</p></div></div><div className="flex items-start gap-3"><span className="rounded-xl bg-blue-50 p-2.5 text-blue-700"><ShieldCheck className="h-5 w-5" /></span><div><p className="text-sm font-semibold text-slate-900">Account safety</p><p className="mt-1 text-xs leading-5 text-slate-500">Never share passwords, PINs or one-time codes.</p></div></div></div>{whatsappNumber && <a href={'https://wa.me/' + whatsappNumber} target="_blank" rel="noopener noreferrer" className="mt-5 flex items-center justify-center gap-2 rounded-xl border border-slate-200 px-4 py-3 text-sm font-bold text-slate-800 hover:bg-slate-50"><MessageCircle className="h-4 w-4 text-emerald-600" /> WhatsApp</a>}{phone && <a href={'tel:' + phone.replace(/[^+\d]/g, '')} className="mt-2 flex items-center justify-center gap-2 rounded-xl border border-slate-200 px-4 py-3 text-sm font-bold text-slate-800 hover:bg-slate-50"><Phone className="h-4 w-4" /> Call support</a>}</div>
        </aside>
      </div>
    </main>
  );
};
