import React, { useState } from 'react';
import { ChevronDown, CircleHelp, MessageCircle, Phone, ShieldCheck, Truck, WalletCards } from 'lucide-react';
import { useDelivery } from '../../context/DeliveryContext';

export const HelpPage: React.FC = () => {
  const { platformSettings, setActivePage } = useDelivery();
  const [openFaq, setOpenFaq] = useState<number | null>(0);
  const faqs = [
    { group: 'Orders & delivery', q: 'Where can I follow my order?', a: 'Open My Orders to view the latest order status and delivery progress. If an order appears stuck, submit a support ticket and include your order reference.' },
    { group: 'Orders & delivery', q: 'Can I cancel an order?', a: 'Cancellation depends on the current order stage and the restaurant’s preparation status. Contact support promptly with your order reference if you need help.' },
    { group: 'Payments & refunds', q: 'What should I do if a payment looks incorrect?', a: 'Do not retry repeatedly if a payment is pending or unclear. Save the transaction reference and submit a Payment or wallet ticket so the team can investigate.' },
    { group: 'Payments & refunds', q: 'How do I report a missing item or request a refund?', a: 'Submit a Refund or missing item ticket. Include your order reference and describe the issue; support will review the order and payment record.' },
    { group: 'Account & privacy', q: 'What information should I send to support?', a: 'Include the email associated with your account and relevant order or transaction references. Never send your password, one-time codes, or full card details.' },
    { group: 'Account & privacy', q: 'How do I see the team’s response?', a: 'Every submitted request has a ticket reference. Use Contact Support to check its status and view the latest reply using that reference and the same email address.' }
  ];
  const whatsappNumber = (platformSettings?.cms_whatsapp_phone || '').replace(/\D/g, '');
  const phone = platformSettings?.cms_support_phone || '';
  return (
    <div className="min-h-[70vh] bg-slate-50 pb-16">
      <section className="bg-slate-950 text-white"><div className="mx-auto max-w-6xl px-5 py-12 sm:px-8 sm:py-14"><p className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/5 px-3 py-1.5 text-xs font-semibold text-orange-200"><CircleHelp className="h-4 w-4" /> HELP CENTRE</p><h1 className="mt-4 text-3xl font-bold tracking-tight sm:text-5xl">{platformSettings?.cms_help_title || 'Help, without the guesswork.'}</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-slate-300 sm:text-base">{platformSettings?.cms_help_subtitle || 'Find answers about orders, delivery, payments and your account. If you need personal assistance, our support team can follow your request through a ticket.'}</p><button onClick={() => setActivePage('contact')} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-orange-600 px-5 py-3 text-sm font-bold text-white hover:bg-orange-700">Contact support <MessageCircle className="h-4 w-4" /></button></div></section>
      <div className="mx-auto grid max-w-6xl gap-8 px-4 py-8 sm:px-8 lg:grid-cols-[minmax(0,1fr)_300px] lg:py-10">
        <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="mb-6"><p className="text-xs font-bold uppercase tracking-widest text-orange-600">Knowledge base</p><h2 className="mt-2 text-2xl font-bold text-slate-950">Frequently asked questions</h2><p className="mt-2 text-sm text-slate-500">Choose a question to see the answer.</p></div><div className="space-y-3">{faqs.map((faq, idx) => { const isOpen = openFaq === idx; return <div key={faq.q} className="overflow-hidden rounded-xl border border-slate-200"><button aria-expanded={isOpen} onClick={() => setOpenFaq(isOpen ? null : idx)} className="flex w-full items-center justify-between gap-4 p-4 text-left hover:bg-slate-50"><span><span className="mb-1 block text-[10px] font-bold uppercase tracking-widest text-orange-600">{faq.group}</span><span className="text-sm font-semibold text-slate-900">{faq.q}</span></span><ChevronDown className={'h-4 w-4 shrink-0 text-slate-500 transition-transform ' + (isOpen ? 'rotate-180' : '')} /></button>{isOpen && <div className="border-t border-slate-100 bg-slate-50/70 px-4 py-4 text-sm leading-6 text-slate-600">{faq.a}</div>}</div>; })}</div></section>
        <aside className="space-y-4"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-bold text-slate-950">Need a person?</h2><p className="mt-2 text-sm leading-6 text-slate-500">For account-specific issues, open a ticket. Your request is recorded for the admin support team and you can check the response later.</p><button onClick={() => setActivePage('contact')} className="mt-4 w-full rounded-xl bg-slate-950 px-4 py-3 text-sm font-bold text-white hover:bg-slate-800">Open a support ticket</button></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><span className="rounded-xl bg-orange-50 p-2.5 text-orange-600"><Truck className="h-5 w-5" /></span><div><h3 className="text-sm font-bold text-slate-900">Order support</h3><p className="mt-1 text-xs leading-5 text-slate-500">Keep your order reference nearby.</p></div></div><div className="my-4 border-t border-slate-100" /><div className="flex items-center gap-3"><span className="rounded-xl bg-emerald-50 p-2.5 text-emerald-700"><WalletCards className="h-5 w-5" /></span><div><h3 className="text-sm font-bold text-slate-900">Payment support</h3><p className="mt-1 text-xs leading-5 text-slate-500">Include transaction references, never card details.</p></div></div><div className="my-4 border-t border-slate-100" /><div className="flex items-center gap-3"><span className="rounded-xl bg-blue-50 p-2.5 text-blue-700"><ShieldCheck className="h-5 w-5" /></span><div><h3 className="text-sm font-bold text-slate-900">Account safety</h3><p className="mt-1 text-xs leading-5 text-slate-500">Support will never ask for your password or OTP.</p></div></div>{whatsappNumber && <a href={'https://wa.me/' + whatsappNumber} target="_blank" rel="noopener noreferrer" className="mt-5 flex items-center justify-center gap-2 rounded-xl border border-slate-200 px-4 py-3 text-sm font-bold text-slate-800 hover:bg-slate-50"><MessageCircle className="h-4 w-4 text-emerald-600" /> WhatsApp</a>}{phone && <a href={'tel:' + phone.replace(/[^+\d]/g, '')} className="mt-2 flex items-center justify-center gap-2 rounded-xl border border-slate-200 px-4 py-3 text-sm font-bold text-slate-800 hover:bg-slate-50"><Phone className="h-4 w-4" /> Call support</a>}</div></aside>
      </div>
    </div>
  );
};
